//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2Try2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronimic { get; set; }
        public System.DateTime DateBirth { get; set; }
        public string Pasport_S { get; set; }
        public string Pasport_N { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public string Guid { get; set; }
        public string Social_sec_number { get; set; }
        public string Ein { get; set; }
        public Nullable<int> SocialTypeId { get; set; }
        public Nullable<int> ContryId { get; set; }
        public string Ua { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual SocialType SocialType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
