//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2Try2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecyclerWork
    {
        public int Id { get; set; }
        public int RecyclerId { get; set; }
        public double Duration { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateStart { get; set; }
        public int ServiceCompleteId { get; set; }
        public int RecyclerResultId { get; set; }
    
        public virtual Recycler Recycler { get; set; }
        public virtual RecyclerResult RecyclerResult { get; set; }
        public virtual ServiceComplete ServiceComplete { get; set; }
    }
}
