//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2Try2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceComplete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceComplete()
        {
            this.RecyclerWork = new HashSet<RecyclerWork>();
        }
    
        public int Id { get; set; }
        public int OrderServiceId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual OrderService OrderService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecyclerWork> RecyclerWork { get; set; }
        public virtual User User { get; set; }
    }
}
